In [ ]:
import pandas as pd
import  textblob as TextBlob
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
im = pd.read_csv("/content/netflix_titles.csv")

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
im.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [ ]:
im.drop(['show_id','date_added','release_year','duration','rating'],axis=1,inplace=True)

KeyError: ignored

In [ ]:
im

show_id  ...                                        description
0         s1  ...  In a future where the elite inhabit an island ...
1         s2  ...  After a devastating earthquake hits Mexico Cit...
2         s3  ...  When an army recruit is found dead, his fellow...
3         s4  ...  In a postapocalyptic world, rag-doll robots hi...
4         s5  ...  A brilliant group of students become card-coun...
...      ...  ...                                                ...
7782   s7783  ...  When Lebanon's Civil War deprives Zozo of his ...
7783   s7784  ...  A scrappy but poor boy worms his way into a ty...
7784   s7785  ...  In this documentary, South African rapper Nast...
7785   s7786  ...  Dessert wizard Adriano Zumbo looks for the nex...
7786   s7787  ...  This documentary delves into the mystique behi...

[7787 rows x 12 columns]

In [ ]:
i=im[im['type']=='Movie']
  

In [102]:
i.reset_index(inplace=True)

ValueError: ignored

In [105]:
i.drop(['level_0','index'],axis=1,inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4174: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


In [106]:
i

type  ...                                    combine-feaures
0     Movie  ...  Jorge Michel Grau,Demián Bichir, Héctor Bonill...
1     Movie  ...  Gilbert Chan,Tedd Chan, Stella Chung, Henley H...
2     Movie  ...  Shane Acker,Elijah Wood, John C. Reilly, Jenni...
3     Movie  ...  Robert Luketic,Jim Sturgess, Kevin Spacey, Kat...
4     Movie  ...  Yasir Al Yasiri,Amina Khalil, Ahmed Dawood, Ta...
...     ...  ...                                                ...
5372  Movie  ...  Peter Hewitt,Tim Allen, Courteney Cox, Chevy C...
5373  Movie  ...  Josef Fares,Imad Creidi, Antoinette Turk, Elia...
5374  Movie  ...  Mozez Singh,Vicky Kaushal, Sarah-Jane Dias, Ra...
5375  Movie  ...  _,Nasty C,_,Documentaries, International Movie...
5376  Movie  ...  Sam Dunn,_,Sam Dunn,Documentaries, Music & Mus...

[5377 rows x 8 columns]

In [ ]:
i.fillna("_",inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,


In [ ]:
i["combine-feaures"]= i['director']+","+i['cast']+","+i['director']+","+i['listed_in']+","+ i['description']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(stop_words='english')

In [83]:
corpus=i['combine-feaures'].values

In [ ]:
tfidf_matrix = tfidf.fit_transform(corpus)

In [ ]:
tfidf_matrix.shape

(5377, 37205)

In [ ]:
tfidf_matrix.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
tfidf.get_feature_names()[:10]

['000', '007', '10', '100', '1000', '10th', '11', '112', '11th', '12']

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
vectorizer

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [ ]:
indices = pd.Series(i.index, index=i['title']).drop_duplicates()

In [ ]:
indices[:10]

title
7:19      1
23:59     2
9         3
21        4
122       6
187       7
706       8
1920      9
1922     10
2,215    13
dtype: int64

# Movie recommendation Based on (Description,Cast,Director and Listing)

## Movies recommendation based on Linear-Kernal

In [ ]:
from sklearn.metrics.pairwise import linear_kernel

In [ ]:
cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)

In [ ]:
cosine_sim

array([[1.00000000e+00, 3.23955471e-03, 8.16866945e-04, ...,
        4.21932744e-03, 4.73970571e-02, 0.00000000e+00],
       [3.23955471e-03, 1.00000000e+00, 1.75284974e-03, ...,
        3.46343602e-03, 5.16162170e-03, 0.00000000e+00],
       [8.16866945e-04, 1.75284974e-03, 1.00000000e+00, ...,
        2.44940908e-02, 1.30152398e-03, 0.00000000e+00],
       ...,
       [4.21932744e-03, 3.46343602e-03, 2.44940908e-02, ...,
        1.00000000e+00, 3.65840215e-02, 3.24535677e-02],
       [4.73970571e-02, 5.16162170e-03, 1.30152398e-03, ...,
        3.65840215e-02, 1.00000000e+00, 6.03344088e-02],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        3.24535677e-02, 6.03344088e-02, 1.00000000e+00]])

In [ ]:
def get_recommendations(title, cosine_sim=cosine_sim):
  idx = indices[title]
  sim_scores = list(enumerate(cosine_sim[idx]))
  sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
  sim_scores = sim_scores[1:11]
  movie_indices = [i[0] for i in sim_scores]
  return i['title'].iloc[movie_indices]

## Get your recommendation below|\/

In [ ]:
get_recommendations('21')

6204                               The Cell
7748                              الف مبروك
5716                            Son Of Adam
1196                         Can’t Complain
2519              Grandmother's Farm Part 2
2518                     Grandmother's Farm
7512    We'll Be Right Back After The Break
977                         Blessed Benefit
2341                              Game Over
2277                       Freej Al Taibeen
Name: title, dtype: object

##Movie Recommendation based on consine_similarity 

In [ ]:
corpus=i['combine-feaures'].values

In [ ]:
X = vectorizer.fit_transform(corpus)
X.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
consine = cosine_similarity(X)

In [ ]:
consine[1]

array([0.08698613, 1.        , 0.05173183, ..., 0.10001389, 0.08802377,
       0.02008859])

In [ ]:
def get_recommendation(title, cosine_sim=consine):
  idx = indices[title]
  sim_scores = list(enumerate(cosine_sim[idx]))
  sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
  sim_scores = sim_scores[1:11]
  movie_indices = [i[0] for i in sim_scores]
  return i['title'].iloc[movie_indices]

## GET recommendation below\/

In [ ]:
get_recommendation('21')

6204                     The Cell
2518           Grandmother's Farm
2519    Grandmother's Farm Part 2
7481                        Warda
5716                  Son Of Adam
2341                    Game Over
2277             Freej Al Taibeen
1196               Can’t Complain
730         Barakah Meets Barakah
5411                Savage Raghda
Name: title, dtype: object

# Tv Shows Recommendation

Getting NetFlix Tv Shows

In [59]:
Tv=im[im['type']=='TV Show']

Reseting Index

In [68]:
V=Tv.reset_index()

In [75]:
V.drop(['index'],axis=1,inplace=True)

In [76]:
V

type  ...                                        description
0     TV Show  ...  In a future where the elite inhabit an island ...
1     TV Show  ...  A genetics professor experiments with a treatm...
2     TV Show  ...  In this dark alt-history thriller, a naïve law...
3     TV Show  ...  Archival video and new interviews examine Mexi...
4     TV Show  ...  As a psychology professor faces Alzheimer's, h...
...       ...  ...                                                ...
2405  TV Show  ...  Strong-willed, middle-class Kashaf and carefre...
2406  TV Show  ...  A quest for freedom and legendary treasure beg...
2407  TV Show  ...  While living alone in a spooky town, a young g...
2408  TV Show  ...  An assortment of talent takes the stage for a ...
2409  TV Show  ...  Dessert wizard Adriano Zumbo looks for the nex...

[2410 rows x 7 columns]

In [77]:
V.fillna("_",inplace=True)

In [78]:
V["combine-feaures"]= V['director']+","+V['cast']+","+V['director']+","+V['listed_in']+","+ V['description']

In [80]:
DES=V['combine-feaures'].values

In [82]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(stop_words='english')

In [81]:
tfidf_matrix = tfidf.fit_transform(DES)

In [84]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
vectorizer

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [85]:
indices = pd.Series(V.index, index=V['title']).drop_duplicates()

# Shows recommendation Based on (Description,Cast,Director and Listing)

In [92]:
 y= vectorizer.fit_transform(DES)
y.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]])

In [93]:
consine = cosine_similarity(y)

In [96]:
def get_SHow_recommendation(title, cosine_sim=consine):
  idx = indices[title]
  sim_scores = list(enumerate(cosine_sim[idx]))
  sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
  sim_scores = sim_scores[1:11]
  SHow_indices = [i[0] for i in sim_scores]
  return i['title'].iloc[SHow_indices]

In [88]:
from sklearn.metrics.pairwise import linear_kernel

In [87]:
cosine_sin = linear_kernel(tfidf_matrix, tfidf_matrix)

In [90]:
def get_show_recommendations(title, cosine_sim=cosine_sin):
  idx = indices[title]
  sim_scores = list(enumerate(cosine_sin[idx]))
  sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
  sim_scores = sim_scores[1:11]
  show_indices = [i[0] for i in sim_scores]
  return i['title'].iloc[show_indices]

## Linear kernal show Recommendation AND COnsine SImilarity Recommendation

In [91]:
get_show_recommendations('Zona Rosa')

2200                             Fiza
1635    David Brent: Life on the Road
464                  American Hangman
2729                 High Flying Bird
1751                  Die Another Day
2702                  Her Only Choice
2507            Goyo: The Boy General
933                    Bir Baba Hindu
466                American History X
2766                         Hokkabaz
Name: title, dtype: object

In [97]:
get_SHow_recommendation('Zona Rosa')

2200                                         Fiza
1310           Chelsea Peretti: One of the Greats
842                            Berlin, I Love You
2272    Free Rein: The Twelve Neighs of Christmas
1286                              Chashme Baddoor
157                                        A Choo
1751                              Die Another Day
943                                   Bittoo Boss
466                            American History X
54                                     100 Meters
Name: title, dtype: object